// End-to-end validation + processor checks against REAL fixture files
// (test/fixtures/, generated by `node scripts/make-fixtures.mjs`).
// Synthetic magic-byte unit tests live in validation.test.ts; this file
// proves genuine containers are accepted and garbage is still rejected.
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { detectKind, validateFile } from './shared/validation';
import { newCancelToken } from './shared/types';
import { extractTar, extractZip } from './processors/archive';
import { textToDocx, textToPdf } from './processors/document';
import JSZip from 'jszip';

const dir = join(dirname(fileURLToPath(import.meta.url)), '..', 'test', 'fixtures');
const load = (name: string, type = ''): File =>
  new File([readFileSync(join(dir, name))], name, { type });

const VID = ['.mp4', '.webm', '.mov', '.m4v', '.mkv', '.avi'];
const AUD = ['.mp3', '.wav', '.m4a', '.aac'];

describe('real containers pass validation', () => {
  it.each([
    ['sample.mp4', 'mp4'],
    ['sample.webm', 'webm'],
    ['sample.mkv', 'mkv'],
    ['sample.avi', 'avi'],
    ['sample.mov', 'mp4'],
    ['sample.m4v', 'mp4'],
  ])('%s detects as %s and validates for video tools', async (name, kind) => {
    const f = load(name);
    expect(await detectKind(f)).toBe(kind);
    expect((await validateFile(f, VID)).ok).toBe(true);
  });

  it.each([
    ['sample.mp3', 'mp3'],
    ['sample.wav', 'wav'],
    ['sample.m4a', 'mp4'],
    ['sample.aac', 'aac'],
  ])('%s detects as %s and validates for audio tools', async (name, kind) => {
    const f = load(name);
    expect(await detectKind(f)).toBe(kind);
    expect((await validateFile(f, AUD)).ok).toBe(true);
  });

  it('m4a (ftyp) validates for the m4a-to-mp3 accept list', async () => {
    expect((await validateFile(load('sample.m4a'), ['.m4a', '.aac'])).ok).toBe(true);
    expect((await validateFile(load('sample.aac'), ['.m4a', '.aac'])).ok).toBe(true);
  });

  it('truncated mp4 head still detects as mp4', async () => {
    const bytes = readFileSync(join(dir, 'sample.mp4')).subarray(0, 8192);
    const f = new File([bytes], 'cut.mp4');
    expect(await detectKind(f)).toBe('mp4');
    expect((await validateFile(f, VID)).ok).toBe(true);
  });

  it('same-family renames still validate; cross-family is rejected', async () => {
    // mp4 bytes named .avi: browsers sniff content, so the family check passes.
    const avi = new File([readFileSync(join(dir, 'sample.mp4'))], 'x.avi');
    expect((await validateFile(avi, VID)).ok).toBe(true);
    // mp4 bytes claimed as audio: content family does not match at all.
    const mp3 = new File([readFileSync(join(dir, 'sample.mp4'))], 'x.mp3');
    expect(await validateFile(mp3, ['.mp3'])).toEqual({ ok: false, error: 'err.corrupted' });
    // mp3 bytes named .wav.
    const wav = new File([readFileSync(join(dir, 'sample.mp3'))], 'x.wav');
    expect(await validateFile(wav, ['.wav'])).toEqual({ ok: false, error: 'err.corrupted' });
  });
});

describe('real archives extract', () => {
  it('extractZip unpacks the real zip', async () => {
    const out = await extractZip(load('sample.zip'), newCancelToken(), () => {});
    expect(out.map((o) => o.name).sort()).toEqual(['dir-nested.txt', 'hello.txt']);
  });

  it.each(['sample.tar', 'sample.tgz', 'sample.tar.gz'])('extractTar unpacks %s', async (name) => {
    expect((await validateFile(load(name), ['.tar', '.tgz', '.tar.gz'])).ok).toBe(true);
    const out = await extractTar(load(name), newCancelToken(), () => {});
    expect(out.map((o) => o.name).sort()).toEqual(['dir-nested.txt', 'hello.txt']);
  });
});

describe('real documents convert', () => {
  it('sample.docx is genuine OOXML with the expected text', async () => {
    // mammoth only runs in the browser build (arrayBuffer support); here we
    // prove the fixture itself is a valid docx carrying the expected content.
    expect((await validateFile(load('sample.docx'), ['.docx'])).ok).toBe(true);
    const zip = await JSZip.loadAsync(load('sample.docx'));
    expect(zip.file('[Content_Types].xml')).not.toBeNull();
    const docXml = zip.file('word/document.xml');
    expect(docXml).not.toBeNull();
    expect(await docXml!.async('text')).toContain('Hello docx world.');
  });

  it.each(['sample.txt', 'sample.md'])('textToPdf renders %s to a real PDF', async (name) => {
    const kind = name.endsWith('.md') ? 'md' : 'txt';
    const out = await textToPdf(load(name), kind as 'txt' | 'md', newCancelToken());
    const head = new Uint8Array(await out.blob.slice(0, 5).arrayBuffer());
    expect(String.fromCharCode(...head)).toBe('%PDF-');
  });

  it('textToDocx round-trips the real txt', async () => {
    const out = await textToDocx(load('sample.txt'), 'txt', newCancelToken());
    expect(out.name).toBe('sample.docx');
    expect(out.size).toBeGreaterThan(1000);
  });
});
